### ISSUE TITLE
Error during 'npm install'

### ISSUE THREAD

**Issue by benjamincharity** [alexperezpaya/Spotijay#3]
Any idea what went wrong for me?

```
    ➜  Spotijay git:(master) npm install
    -
    > libspotify@0.2.2 install /Users/ME/Dropbox/Spotijay/node_modules/libspotify
    > node-gyp configure build

      CXX(target) Release/obj.target/libspotify/src/album.o
    In file included from ../src/album.cc:20:
    ../src/common.h:23:10: fatal error: 'libspotify/api.h' file not found
#include <libspotify/api.h>
             ^
    1 error generated.
    make: *** [Release/obj.target/libspotify/src/album.o] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
    gyp ERR! System Darwin 13.3.0
    gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
    gyp ERR! cwd /Users/ME/Dropbox/Spotijay/node_modules/libspotify
    gyp ERR! node -v v0.10.30
    gyp ERR! node-gyp -v v0.13.1
    gyp ERR! not ok
    npm ERR! libspotify@0.2.2 install: `node-gyp configure build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the libspotify@0.2.2 install script.
    npm ERR! This is most likely a problem with the libspotify package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp configure build
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls libspotify
    npm ERR! There is likely additional logging output above.

    npm ERR! System Darwin 13.3.0
    npm ERR! command "node" "/usr/local/bin/npm" "install"
    npm ERR! cwd /Users/bc/Dropbox/Spotijay
    npm ERR! node -v v0.10.30
    npm ERR! npm -v 2.0.0-alpha-5
    npm ERR! code ELIFECYCLE
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     /Users/ME/Dropbox/Spotijay/npm-debug.log
    npm ERR! not ok code 0
```

**Comment by timpoultney** [comment]
1) Download binary from Spotify
2) Unpack libspotify.framework into /Library/Frameworks
3) sudo ln -s /Library/Frameworks/libspotify.framework/libspotify /usr/local/lib/libspotify.dylib

**Comment by alexperezpaya** [comment]
@timpoultney Thank you! I fixed my own a long time ago, but I forgot to post it here.

**Comment by lfsanchezg** [comment]
Hi, I tried to install Spotijay today and got this error

```

> libspotify@0.2.2 install /Users/felipe/Spotijay/node_modules/libspotify
> node-gyp configure build

  CXX(target) Release/obj.target/libspotify/src/album.o
In file included from ../src/album.cc:20:
../src/common.h:45:42: error: no member named 'New' in 'v8::String'; did you mean 'v8::TypeSwitch::New'?
    v8::Handle<v8::Value> value = o->Get(v8::String::New(name));
                                         ^~~~~~~~~~~~~~~
                                         v8::TypeSwitch::New
/Users/felipe/.node-gyp/4.1.2/include/node/v8.h:4705:28: note: 'v8::TypeSwitch::New' declared here
  static Local<TypeSwitch> New(Local<FunctionTemplate> type);
                           ^
In file included from ../src/album.cc:20:
../src/common.h:45:58: error: calling a private constructor of class 'v8::Local<v8::FunctionTemplate>'
    v8::Handle<v8::Value> value = o->Get(v8::String::New(name));
                                                         ^
/Users/felipe/.node-gyp/4.1.2/include/node/v8.h:326:13: note: declared private here
  V8_INLINE Local(S* that)
            ^
In file included from ../src/album.cc:20:
../src/common.h:58:42: error: no member named 'New' in 'v8::String'; did you mean 'v8::TypeSwitch::New'?
    v8::Handle<v8::Value> value = o->Get(v8::String::New(name));
                                         ^~~~~~~~~~~~~~~
                                         v8::TypeSwitch::New
/Users/felipe/.node-gyp/4.1.2/include/node/v8.h:4705:28: note: 'v8::TypeSwitch::New' declared here
  static Local<TypeSwitch> New(Local<FunctionTemplate> type);
                           ^
In file included from ../src/album.cc:20:
../src/common.h:58:58: error: calling a private constructor of class 'v8::Local<v8::FunctionTemplate>'
    v8::Handle<v8::Value> value = o->Get(v8::String::New(name));
                                                         ^
/Users/felipe/.node-gyp/4.1.2/include/node/v8.h:326:13: note: declared private here
  V8_INLINE Local(S* that)
            ^
In file included from ../src/album.cc:20:
../src/common.h:74:42: error: no member named 'New' in 'v8::String'; did you mean 'v8::TypeSwitch::New'?
    v8::Handle<v8::Value> value = o->Get(v8::String::New(name));
                                         ^~~~~~~~~~~~~~~
                                         v8::TypeSwitch::New
/Users/felipe/.node-gyp/4.1.2/include/node/v8.h:4705:28: note: 'v8::TypeSwitch::New' declared here
  static Local<TypeSwitch> New(Local<FunctionTemplate> type);
                           ^
In file included from ../src/album.cc:20:
../src/common.h:74:58: error: calling a private constructor of class 'v8::Local<v8::FunctionTemplate>'
    v8::Handle<v8::Value> value = o->Get(v8::String::New(name));
                                                         ^
/Users/felipe/.node-gyp/4.1.2/include/node/v8.h:326:13: note: declared private here
  V8_INLINE Local(S* that)
            ^
In file included from ../src/album.cc:20:
../src/common.h:81:29: error: no member named 'AsciiValue' in 'v8::String'
    strcpy(v, *(v8::String::AsciiValue(value)));
                ~~~~~~~~~~~~^
../src/common.h:93:42: error: no member named 'New' in 'v8::String'; did you mean 'v8::TypeSwitch::New'?
    v8::Handle<v8::Value> value = o->Get(v8::String::New(name));
                                         ^~~~~~~~~~~~~~~
                                         v8::TypeSwitch::New
/Users/felipe/.node-gyp/4.1.2/include/node/v8.h:4705:28: note: 'v8::TypeSwitch::New' declared here
  static Local<TypeSwitch> New(Local<FunctionTemplate> type);
                           ^
In file included from ../src/album.cc:20:
../src/common.h:93:58: error: calling a private constructor of class 'v8::Local<v8::FunctionTemplate>'
    v8::Handle<v8::Value> value = o->Get(v8::String::New(name));
                                                         ^
/Users/felipe/.node-gyp/4.1.2/include/node/v8.h:326:13: note: declared private here
  V8_INLINE Local(S* that)
            ^
In file included from ../src/album.cc:20:
../src/common.h:107:42: error: no member named 'New' in 'v8::String'; did you mean 'v8::TypeSwitch::New'?
    v8::Handle<v8::Value> value = o->Get(v8::String::New(name));
                                         ^~~~~~~~~~~~~~~
                                         v8::TypeSwitch::New
/Users/felipe/.node-gyp/4.1.2/include/node/v8.h:4705:28: note: 'v8::TypeSwitch::New' declared here
  static Local<TypeSwitch> New(Local<FunctionTemplate> type);
                           ^
In file included from ../src/album.cc:20:
../src/common.h:107:58: error: calling a private constructor of class 'v8::Local<v8::FunctionTemplate>'
    v8::Handle<v8::Value> value = o->Get(v8::String::New(name));
                                                         ^
/Users/felipe/.node-gyp/4.1.2/include/node/v8.h:326:13: note: declared private here
  V8_INLINE Local(S* that)
            ^
In file included from ../src/album.cc:20:
../src/common.h:121:40: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    v8::Handle<v8::Value> JsNoOp(const v8::Arguments&);
                                       ^~~~~~~~~~~~~
                                       v8::internal::Arguments
/Users/felipe/.node-gyp/4.1.2/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/album.cc:20:
../src/common.h:210:45: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
            v8::Handle<v8::Value> New(const v8::Arguments& args) {
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/felipe/.node-gyp/4.1.2/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/album.cc:20:
../src/common.h:213:28: error: member access into incomplete type 'const v8::internal::Arguments'
                return args.This();
                           ^
/Users/felipe/.node-gyp/4.1.2/include/node/v8.h:139:7: note: forward declaration of
      'v8::internal::Arguments'
class Arguments;
      ^
In file included from ../src/album.cc:20:
../src/common.h:219:73: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of
      type 'v8::Handle<v8::Value> (const v8::internal::Arguments &)'
        v8::Local<v8::FunctionTemplate> tpl = v8::FunctionTemplate::New(JsNoOp);
                                                                        ^~~~~~
/Users/felipe/.node-gyp/4.1.2/include/node/v8.h:4350:16: note: passing argument to parameter 'isolate'
      here
      Isolate* isolate, FunctionCallback callback = 0,
               ^
In file included from ../src/album.cc:20:
../src/common.h:221:25: error: no member named 'NewSymbol' in 'v8::String'
            v8::String::NewSymbol(name == NULL ? "CObject" : name)
            ~~~~~~~~~~~~^
../src/common.h:228:69: error: too few arguments to function call, expected 2, have 1
        object = v8::Persistent<v8::Object>::New(otpl->NewInstance());
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                    ^
/Users/felipe/.node-gyp/4.1.2/include/node/v8.h:639:3: note: 'New' declared here
  V8_INLINE static T* New(Isolate* isolate, T* that);
  ^
/Users/felipe/.node-gyp/4.1.2/include/node/v8config.h:301:20: note: expanded from macro 'V8_INLINE'
# define V8_INLINE inline __attribute__((always_inline))
                   ^
In file included from ../src/album.cc:20:
../src/common.h:230:15: error: member reference type 'v8::Persistent<v8::Object>' is not a pointer; maybe
      you meant to use '.'?
        object->SetPointerInInternalField(0, this);
        ~~~~~~^~
              .
../src/common.h:230:17: error: no member named 'SetPointerInInternalField' in 'v8::Persistent<v8::Object,
      v8::NonCopyablePersistentTraits<v8::Object> >'
        object->SetPointerInInternalField(0, this);
        ~~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/libspotify/src/album.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/4.1.2/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/felipe/Spotijay/node_modules/libspotify
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.1.2/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.6
npm ERR! code ELIFECYCLE

npm ERR! libspotify@0.2.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libspotify@0.2.2 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the libspotify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls libspotify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/felipe/Spotijay/npm-debug.log

```

I tried getting libspotify using brew, and then tried the manual installation copying the framework file as listed above, but I can't get it to install. Do you have any tip for this? I'm new to node xC

**Comment by alexperezpaya** [comment]
I belive this issue its regarding a dependency of this currently unmaintained project (node libspotify)

I'll try to have a look at it, but don't expect anything, I'm not considering to continue with this project.

**Comment by lfsanchezg** [comment]
Oh Alex, I got to get a similar project working :D , please don't bother, I forgot to delete this comment 😓
